### ISSUE TITLE
Request: Allow specifying the parent element

### ISSUE THREAD

**Issue by nogweii** [zacharyvoase/jsonpipe#1]
Sometimes it's nice to not have to grep the output afterward, but instead you can specify where jsonpipe considers the top element, only showing the children.

For example, given this input: (yes, ripped from your README :-) )

```
$ echo '[{"a": [{"b": {"c": ["foo"]}}]}]' | jsonpipe '/0/a/0/b'
```

jsonpipe would output the following:

```
/       {}
/c      []
/c/0    "foo"
```

Thus, only showing a subset of the entire JSON document.

**Comment by zacharyvoase** [comment]
This is outside the scope of what jsonpipe does. The raison d’être of the utility is to make JSON easier to grep, not to _actually_ grep it for you.
